# Generated by Django 4.0.3 on 2022-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='numero')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='cep')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Médio')),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
