# Generated by Django 4.0.3 on 2022-04-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0003_alter_inscricao_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
    ]
