# Generated by Django 4.0.3 on 2022-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_alter_inscricao_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='fim_inscricao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
