# Generated by Django 4.0.3 on 2022-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_inscricao_fim_inscricao_inscricao_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FimInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('fim_inscricao', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='fim_inscricao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='texto',
        ),
    ]
