# Generated by Django 4.0.3 on 2022-04-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0006_fiminscricao_remove_inscricao_fim_inscricao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FimInscricao',
            new_name='FimInscricoes',
        ),
        migrations.AlterModelOptions(
            name='fiminscricoes',
            options={'ordering': ('id',)},
        ),
    ]
