# Generated by Django 4.0.3 on 2022-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_rename_fiminscricao_fiminscricoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiminscricoes',
            name='texto',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
