# Generated by Django 4.0.3 on 2022-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0008_alter_fiminscricoes_texto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiminscricoes',
            options={},
        ),
        migrations.RenameField(
            model_name='fiminscricoes',
            old_name='texto',
            new_name='aviso',
        ),
        migrations.AlterField(
            model_name='fiminscricoes',
            name='fim_inscricao',
            field=models.BooleanField(default=False),
        ),
    ]
